version: "3.7"
services:
  app: # PHP & NodeJS Service; name of our app, there is just one indicated
    build:
      context: .
    tty: true
    restart: unless-stopped
    working_dir: /programming-proficiency-test
    volumes:
      - ./:/programming-proficiency-test
    ports:
      - "8080:8080"
      - "3000:3000"
